version: "3"

services: 
  app: 
    build: 
      context: ./node
    networks: 
      - node_network
    tty: true
    container_name: fullcycle_docker_node_desafio_node
    depends_on: 
      - db

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: fullcycle_docker_node_desafio_mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node_network

  nginx: 
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: fullcycle_docker_node_desafio_nginx
    networks: 
      - node_network
    restart: always
    ports: 
      - "8080:80"
    depends_on: 
      - app

networks: 
  node_network:
    driver: bridge